/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FilteringWithTanstackQueryRouteImport } from './routes/filtering-with-tanstack-query/route'
import { Route as FilteringPrefetchInRenderRouteImport } from './routes/filtering-prefetch-in-render/route'
import { Route as FilteringRouteImport } from './routes/filtering/route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FilteringWithTanstackQueryRouteRoute =
  FilteringWithTanstackQueryRouteImport.update({
    id: '/filtering-with-tanstack-query',
    path: '/filtering-with-tanstack-query',
    getParentRoute: () => rootRoute,
  } as any)

const FilteringPrefetchInRenderRouteRoute =
  FilteringPrefetchInRenderRouteImport.update({
    id: '/filtering-prefetch-in-render',
    path: '/filtering-prefetch-in-render',
    getParentRoute: () => rootRoute,
  } as any)

const FilteringRouteRoute = FilteringRouteImport.update({
  id: '/filtering',
  path: '/filtering',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/filtering': {
      id: '/filtering'
      path: '/filtering'
      fullPath: '/filtering'
      preLoaderRoute: typeof FilteringRouteImport
      parentRoute: typeof rootRoute
    }
    '/filtering-prefetch-in-render': {
      id: '/filtering-prefetch-in-render'
      path: '/filtering-prefetch-in-render'
      fullPath: '/filtering-prefetch-in-render'
      preLoaderRoute: typeof FilteringPrefetchInRenderRouteImport
      parentRoute: typeof rootRoute
    }
    '/filtering-with-tanstack-query': {
      id: '/filtering-with-tanstack-query'
      path: '/filtering-with-tanstack-query'
      fullPath: '/filtering-with-tanstack-query'
      preLoaderRoute: typeof FilteringWithTanstackQueryRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filtering': typeof FilteringRouteRoute
  '/filtering-prefetch-in-render': typeof FilteringPrefetchInRenderRouteRoute
  '/filtering-with-tanstack-query': typeof FilteringWithTanstackQueryRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filtering': typeof FilteringRouteRoute
  '/filtering-prefetch-in-render': typeof FilteringPrefetchInRenderRouteRoute
  '/filtering-with-tanstack-query': typeof FilteringWithTanstackQueryRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/filtering': typeof FilteringRouteRoute
  '/filtering-prefetch-in-render': typeof FilteringPrefetchInRenderRouteRoute
  '/filtering-with-tanstack-query': typeof FilteringWithTanstackQueryRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/filtering'
    | '/filtering-prefetch-in-render'
    | '/filtering-with-tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/filtering'
    | '/filtering-prefetch-in-render'
    | '/filtering-with-tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/filtering'
    | '/filtering-prefetch-in-render'
    | '/filtering-with-tanstack-query'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilteringRouteRoute: typeof FilteringRouteRoute
  FilteringPrefetchInRenderRouteRoute: typeof FilteringPrefetchInRenderRouteRoute
  FilteringWithTanstackQueryRouteRoute: typeof FilteringWithTanstackQueryRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilteringRouteRoute: FilteringRouteRoute,
  FilteringPrefetchInRenderRouteRoute: FilteringPrefetchInRenderRouteRoute,
  FilteringWithTanstackQueryRouteRoute: FilteringWithTanstackQueryRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/filtering",
        "/filtering-prefetch-in-render",
        "/filtering-with-tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/filtering": {
      "filePath": "filtering/route.tsx"
    },
    "/filtering-prefetch-in-render": {
      "filePath": "filtering-prefetch-in-render/route.tsx"
    },
    "/filtering-with-tanstack-query": {
      "filePath": "filtering-with-tanstack-query/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
