/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FilteringWithoutStreamingRouteRouteImport } from './routes/filtering-without-streaming/route'
import { Route as FilteringWithUsesuspenseQueryRouteRouteImport } from './routes/filtering-with-usesuspense-query/route'
import { Route as FilteringWithUsequeryPromiseRouteRouteImport } from './routes/filtering-with-usequery-promise/route'
import { Route as FilteringRouteRouteImport } from './routes/filtering/route'
import { Route as IndexRouteImport } from './routes/index'

const FilteringWithoutStreamingRouteRoute =
  FilteringWithoutStreamingRouteRouteImport.update({
    id: '/filtering-without-streaming',
    path: '/filtering-without-streaming',
    getParentRoute: () => rootRouteImport,
  } as any)
const FilteringWithUsesuspenseQueryRouteRoute =
  FilteringWithUsesuspenseQueryRouteRouteImport.update({
    id: '/filtering-with-usesuspense-query',
    path: '/filtering-with-usesuspense-query',
    getParentRoute: () => rootRouteImport,
  } as any)
const FilteringWithUsequeryPromiseRouteRoute =
  FilteringWithUsequeryPromiseRouteRouteImport.update({
    id: '/filtering-with-usequery-promise',
    path: '/filtering-with-usequery-promise',
    getParentRoute: () => rootRouteImport,
  } as any)
const FilteringRouteRoute = FilteringRouteRouteImport.update({
  id: '/filtering',
  path: '/filtering',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/filtering': typeof FilteringRouteRoute
  '/filtering-with-usequery-promise': typeof FilteringWithUsequeryPromiseRouteRoute
  '/filtering-with-usesuspense-query': typeof FilteringWithUsesuspenseQueryRouteRoute
  '/filtering-without-streaming': typeof FilteringWithoutStreamingRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/filtering': typeof FilteringRouteRoute
  '/filtering-with-usequery-promise': typeof FilteringWithUsequeryPromiseRouteRoute
  '/filtering-with-usesuspense-query': typeof FilteringWithUsesuspenseQueryRouteRoute
  '/filtering-without-streaming': typeof FilteringWithoutStreamingRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/filtering': typeof FilteringRouteRoute
  '/filtering-with-usequery-promise': typeof FilteringWithUsequeryPromiseRouteRoute
  '/filtering-with-usesuspense-query': typeof FilteringWithUsesuspenseQueryRouteRoute
  '/filtering-without-streaming': typeof FilteringWithoutStreamingRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/filtering'
    | '/filtering-with-usequery-promise'
    | '/filtering-with-usesuspense-query'
    | '/filtering-without-streaming'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/filtering'
    | '/filtering-with-usequery-promise'
    | '/filtering-with-usesuspense-query'
    | '/filtering-without-streaming'
  id:
    | '__root__'
    | '/'
    | '/filtering'
    | '/filtering-with-usequery-promise'
    | '/filtering-with-usesuspense-query'
    | '/filtering-without-streaming'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilteringRouteRoute: typeof FilteringRouteRoute
  FilteringWithUsequeryPromiseRouteRoute: typeof FilteringWithUsequeryPromiseRouteRoute
  FilteringWithUsesuspenseQueryRouteRoute: typeof FilteringWithUsesuspenseQueryRouteRoute
  FilteringWithoutStreamingRouteRoute: typeof FilteringWithoutStreamingRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/filtering-without-streaming': {
      id: '/filtering-without-streaming'
      path: '/filtering-without-streaming'
      fullPath: '/filtering-without-streaming'
      preLoaderRoute: typeof FilteringWithoutStreamingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filtering-with-usesuspense-query': {
      id: '/filtering-with-usesuspense-query'
      path: '/filtering-with-usesuspense-query'
      fullPath: '/filtering-with-usesuspense-query'
      preLoaderRoute: typeof FilteringWithUsesuspenseQueryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filtering-with-usequery-promise': {
      id: '/filtering-with-usequery-promise'
      path: '/filtering-with-usequery-promise'
      fullPath: '/filtering-with-usequery-promise'
      preLoaderRoute: typeof FilteringWithUsequeryPromiseRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filtering': {
      id: '/filtering'
      path: '/filtering'
      fullPath: '/filtering'
      preLoaderRoute: typeof FilteringRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilteringRouteRoute: FilteringRouteRoute,
  FilteringWithUsequeryPromiseRouteRoute:
    FilteringWithUsequeryPromiseRouteRoute,
  FilteringWithUsesuspenseQueryRouteRoute:
    FilteringWithUsesuspenseQueryRouteRoute,
  FilteringWithoutStreamingRouteRoute: FilteringWithoutStreamingRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
